# Lecture 8.Solving Ax = b: row reduced form R

In [2]:
A = [1 2 2 2;2 4 6 8; 3 6 8 10]

A =

    1    2    2    2
    2    4    6    8
    3    6    8   10



&emsp;$x_1 + 2x_2 + 2x_3 + 2x_4 = b_1$<br>
$2x_1 + 4x_2 + 6x_3 + 8x_4 = b_2$<br>
$3x_1 + 6x_2 + 8x_3 + 10x_4 = b_3$<br>

The augmented matrix is = $[A b]$

$
\begin{bmatrix}
   1 & 2 & 2 & 2 & b_1 \\
   2 & 4 & 6 & 8 & b_2 \\
   3 & 6 & 8 & 10 & b_3 \\   
\end{bmatrix}$ by eliminatin we have

$\begin{bmatrix}
   1 & 2 & 2 & 2 & b_1 \\
   0 & 0 & 2 & 4 & b_2-2b_1 \\
   0 & 0 & 2 & 4 & b_3-3b_1 \\   
\end{bmatrix} \rightarrow
\begin{bmatrix}
   1 & 2 & 2 & 2 & b_1 \\
   0 & 0 & 2 & 4 & b_2-2b_1 \\
   0 & 0 & 0 & 0 & b_3-b_2-b_1 \\   
\end{bmatrix}
$

The last equation is

$0 = b_3 - b_2 - b_1$, that's the condition for solvability, and if our numbers happen to have been 1, 5, 6

$b = 
\begin{bmatrix}
   1 \\
   5 \\
   6 \\   
\end{bmatrix}
$

$ \rightarrow
\begin{bmatrix}
   1 & 2 & 2 & 2 & 1 \\
   0 & 0 & 2 & 4 & 3 \\
   0 & 0 & 0 & 0 & 0 \\   
\end{bmatrix}
$



## Solvability. Condition on b

Ax = b solvable when:

* b in in C(A)
* If a comb. of the rows of A gives 0 row, then the same comb. of the components of b must give 0

The two statements are equivalent

### To find the complete sol'n to Ax=b

1.- One particular solution $x_{particular}$: 

* Set all free variables to zero<br>
* Solve Ax=b for pivot variables

In our example:

Free variables $x_2 = 0$ and $x_4 = 0$

$ x_1 + 2x_3 = 1$<br>
$\hspace{1cm} 2x_3 = 3$<br>
$x_3 = 3/2 \ and \ x_1 = -2$


$x_{particular} = x_p = 
\begin{bmatrix}
   -2 \\
    0 \\
   3/2 \\
    0 \\   
\end{bmatrix}
$

How I find the rest?

2.- $x_{nullspace} = x_n$: 

The complete solution $x$ will be $x = x_p + x_n$

$Ax_p = b$<br>
$Ax_n = 0$<br>
$A(x_p + x_n) = b$<br>

$x_c = 
\begin{bmatrix}
   -2 \\
    0 \\
   3/2 \\
    0 \\   
\end{bmatrix}
+ c_1
\begin{bmatrix}
   -2 \\
    1 \\
    0 \\
    0 \\   
\end{bmatrix}
+ c_2
\begin{bmatrix}
    2 \\
    0 \\
   -2 \\
    1 \\   
\end{bmatrix}
$


We have a $m times n$ matrix $A$ o rank r (know $r \leq m, r \leq n$) 

Full column ranls $r=n$: No free variables. $N(A)=0, zero vectot$<br>
$x_c = x_p$, unique solution if it exists

#### Example


In [9]:
A = [1 2 6 5 3 1 1 1]; %full column rank
A = reshape(A, [4 2])

A =

   1   3
   2   1
   6   1
   5   1



In [8]:
R = rref(A)

R =

   1   0
   0   1
   0   0
   0   0



Particular solution: sum of column1 and column 2

$ b = 
\begin{bmatrix}
    4 \\
    3 \\
    7 \\
    6 \\   
\end{bmatrix}
$


#### Example

Full row rank $r = m, m$ pivots

$Ax = b$ for every b

Left with $n - m$ free variables

In [2]:
A = [1 2 6 5; 3 1 1 1]

A =

   1   2   6   5
   3   1   1   1



In [3]:
rank(A)

ans = 2


In [6]:
R = rref(A)

R =

   1.0000        0  -0.8000  -0.6000
        0   1.0000   3.4000   2.8000



In [8]:
F = [R(1,3:4); R(2,3:4)]

F =

  -0.8000  -0.6000
   3.4000   2.8000



and we look for solutions in $N$

#### Exercise 

$r =m = n$

A is invertible

In [10]:
A = [ 1 2; 3 1]

A =

   1   2
   3   1



In [12]:
rank(A) % full rank

ans = 2


In [14]:
R = rref(A) % identity matrix

R =

   1   0
   0   1



The null space of A is vector 0

no condition in b

## Summary

1. $r = m = n: R = I$, 1 solution
1. $ r = n < m. R = 
\begin{bmatrix}
    I \\
    0 \\
\end{bmatrix}$, 0 or 1 solution
1. $r = m < n. 
\begin{bmatrix}
    I & 0\\
\end{bmatrix}$, full row rank, the F could be part of I, 1 or $\infty$ solutions 
1. $r <n and r<n. R =
\begin{bmatrix}
    I & F\\
    0 & 0\\    
\end{bmatrix}$, 0 or $\infty$ solutions

Rank tell us everything about the number of solutions
