# Chapter 2. Solving Linear Equations
## Matrix multiplication

In [2]:
A = rand(3,3);
B = rand(3,3);

In [3]:
AB = A * B;
disp(AB)

   0.3472   1.0124   1.1816
   0.6525   0.8200   1.1775
   0.4718   0.8525   1.0935


In [4]:
# 1. The entry in row i and column j of AB is (row i of A) · ( column j of B)
[r,c] = size(A);
AB = nan(r, c);
for i = 1:r
     for j = 1:c
         AB(i,j) = dot(A(i,:), B(:,j));
     end
 end
 disp(AB)

   0.3472   1.0124   1.1816
   0.6525   0.8200   1.1775
   0.4718   0.8525   1.0935


In [5]:
# 2. Matrix A times every column of B
AB = [A * B(:,1),A * B(:,2),A * B(:,3)];
disp(AB)

   0.3472   1.0124   1.1816
   0.6525   0.8200   1.1775
   0.4718   0.8525   1.0935


In [6]:
# 3. Every row of A times matrix B
AB = [A(1,:)*B; A(2,:)*B; A(3,:)*B];
disp(AB)

   0.3472   1.0124   1.1816
   0.6525   0.8200   1.1775
   0.4718   0.8525   1.0935


In [7]:
# 4. Multiply columns 1 to n of A times rows 1 to n of B. Add those matrices
AB = zeros(r, c);
for i = 1:r
     AB = AB + (A(:,i) * B(i,:));
 end
 disp(AB)

   0.3472   1.0124   1.1816
   0.6525   0.8200   1.1775
   0.4718   0.8525   1.0935


## The Matrix Form of One Elimination Step

In [8]:
A = [2, 4, -2; 4, 9, -3; -2, -3, 7];
b = [2; 8; 19];
Ab=[A,b];
disp(Ab)

    2    4   -2    2
    4    9   -3    8
   -2   -3    7   19


In [9]:
E21 = eye(size(A));
E21(2,1) = -2;
Ab1 = E21*Ab;
disp(Ab1)

    2    4   -2    2
    0    1    1    4
   -2   -3    7   19


In [10]:
E31 = eye(size(A));
E31(3,1) = 1;
Ab2 = E31*Ab1;
disp(Ab2)

    2    4   -2    2
    0    1    1    4
    0    1    5   21


In [11]:
E32 = eye(size(A));
E32(3,2) = -1;
Ab3=E32*Ab2;
disp(Ab3)

    2    4   -2    2
    0    1    1    4
    0    0    4   17


In [12]:
E=E32*E31*E21;
disp(E)

   1   0   0
  -2   1   0
   3  -1   1


In [13]:
disp(E*Ab)

    2    4   -2    2
    0    1    1    4
    0    0    4   17


## Inverse matrix

### Calculating $A^{-1}$ by Gauss-Jordan elimination

In [14]:
K = [2, -1, 0; -1, 2, -1; 0, -1, 2 ];
E = eye(size(K));

In [15]:
A = [K, E];  # same as [K, E(:,1), E(:,2), E(:,3)];
disp(A)

   2  -1   0   1   0   0
  -1   2  -1   0   1   0
   0  -1   2   0   0   1


#### Gauss elimination

In [16]:
E21 = eye(3);
E21(2,1) = 1/2;
A1 = E21*A;
disp(A1)

   2.0000  -1.0000        0   1.0000        0        0
        0   1.5000  -1.0000   0.5000   1.0000        0
        0  -1.0000   2.0000        0        0   1.0000


In [17]:
E32 = eye(3);
E32(3,2) = 1/1.5;
A2 = E32*A1;
disp(A2)  # A2 is upper tringular UT

   2.0000  -1.0000        0   1.0000        0        0
        0   1.5000  -1.0000   0.5000   1.0000        0
        0        0   1.3333   0.3333   0.6667   1.0000


#### Jordan elimination

In [18]:
E23 = eye(3);
E23(2,3) = 1/1.3333;
A3 = E23*A2;
disp(A3)

   2.0000  -1.0000        0   1.0000        0        0
        0   1.5000   0.0000   0.7500   1.5000   0.7500
        0        0   1.3333   0.3333   0.6667   1.0000


In [19]:
E12 = eye(3);
E12(1,2) = 1/1.5;
A4 = E12*A3;
disp(A4)  # A4 is a diagonal matrix

   2.0000  -0.0000   0.0000   1.5000   1.0000   0.5000
        0   1.5000   0.0000   0.7500   1.5000   0.7500
        0        0   1.3333   0.3333   0.6667   1.0000


In [20]:
# we divide each row by the element in its diagonal
A4_diag = diag(A4);
A5 = nan(size(A4));
for i = 1:rows(A4)
    A5(i,:) = A4(i,:)/A4_diag(i); 
end
disp(A5)  # The 3 columns on the left form the identity matrix 

   1.0000  -0.0000   0.0000   0.7500   0.5000   0.2500
        0   1.0000   0.0000   0.5000   1.0000   0.5000
        0        0   1.0000   0.2500   0.5000   0.7500


A5(:,4:6) is equal to inv(K)

In [21]:
disp(inv(K))

   0.7500   0.5000   0.2500
   0.5000   1.0000   0.5000
   0.2500   0.5000   0.7500


* If K is symetric $K^-1$ is also symetric
* Although K is not dense (tridiagonal) $K^-1$ is dense
* The product of pivots = determinant of K: we test below

In [22]:
det(K)
prod(diag(A4))

ans = 4.0000
ans = 4


In [23]:
# Anoher way
n = size(K,1);
I = eye(n);
R = rref ([A I]);  # Eliminate on the augmented matrix [A J]
X = R( : , n + 1 : n + n);  # Pick X = A- 1 from the last n columns of R
disp(X)

   0.7500   0.5000   0.2500
   0.5000   1.0000   0.5000
   0.2500   0.5000   0.7500


### Recognizing an Invertible Matrix
* The usual way is to find a full set of nonzero pivots in elimination
* Diagonally dominant matrices are invertible

**Full set of nonzero pivots in elimination**

In [24]:
L = [1, 0, 0; 3, 1, 0; 4, 5, 1] ;
n=size(L, 1);
I = eye(n);
A = [L, I];
disp(A)

   1   0   0   1   0   0
   3   1   0   0   1   0
   4   5   1   0   0   1


In [25]:
A1 = rref(A)(:,n+1:n+n);
disp(A1)

    1.0000         0         0
   -3.0000    1.0000         0
   11.0000   -5.0000    1.0000


In [26]:
find(diag(A1) == 0)

ans = [](0x1)


**Diagonally dominant matrices are invertible**

In [27]:
# A = [3, 1, 1; 1, 3, 1;1, 1, 3];
A = [2, 1, 1; 1, 2, 1;1, 1, 3];
# to be diagonally dominant all elements of the comparyson must be 1
d = abs(diag(A));
s=sum(abs(A),2)-d;
d>s

ans =

  0
  0
  1



In [28]:
# if your matrix is large you can use find 
disp(find(d>s==0))

   1
   2


## Elimination = Factorization: A = LU

* Every inverse matrix $E^{-1}$ is lower triangular. Its off-diagonal entry is $l_{ij}$. The main diagonals of $E$ and $E^{-1}$ contain 1's
* $(E32*E21)^{-1}=E21^{-1} * E32^{-1}L$

In [29]:
A = [2 1 0; 1 2 1; 0 1 2];
disp(A)

   2   1   0
   1   2   1
   0   1   2


In [30]:
E21 = eye(size(A)); E21(2,1) = -1/2; disp(E21*A)

   2.0000   1.0000        0
        0   1.5000   1.0000
        0   1.0000   2.0000


In [31]:
E32 = eye(n); E32(3,2) = -1/1.5 ;
disp(E32*E21*A)
U = E32*E21*A;

   2.0000   1.0000        0
        0   1.5000   1.0000
        0        0   1.3333


The matrix L contains our memory of Gaussian elimination. Notice that $-l_{21} = e_{21}$ and $-l_{32} = e_{32}$  

In [32]:
L = inv(E21)*inv(E32);
disp(L)

   1.0000        0        0
   0.5000   1.0000        0
        0   0.6667   1.0000


$ A = L * U$

In [33]:
disp([A - L*U])

   0   0   0
   0   0   0
   0   0   0


**The triangular factorization can be written $A= LU$ or $A= LDU$**

In [34]:
A = [2 1 0; 1 2 1; 0 1 2];

E21 = eye(n); E32 = eye(n);
E21(2,1) = -1/2; E32(3,2) = -1/1.5;
U = E32*E21*A;

L = inv(E21)*inv(E32);

d = diag(U);
D = eye(size(A)) .* d;

Unew = U ./ d;

disp(A - [L*D*Unew])

   0   0   0
   0   0   0
   0   0   0


### To solve $A x = b$, $L$ and $U$ matrices are required

1. Factor $A$ into $U$ and $L$
1. Solve: forward elimination on $b$ using $L$, then back substitution for $x$ using $U$

In [35]:
A = [1 2;4 9]; disp(A)
b = [5; 21];
K = [A bb];

   1   2
   4   9
error: 'bb' undefined near line 1, column 1


Solve $Lc = b$ 

In [36]:
E21 = eye(size(A));
E21(2,1) = -4;
U = E21*K; disp(U)

error: operator *: nonconformant arguments (op1 is 2x2, op2 is 3x3)


In [37]:
L=inv(E21); disp(L)

   1   0
   4   1


In [38]:
c=U(:, 3); disp(c)

        0
   1.0000
   1.3333


Solve $Ux = c$ 

In [39]:
U = U(:,1:2);

In [40]:
x = inv(U) * c

error: inverse: A must be a square matrix


**Exercise: factorization of Pascal matrix**

L and U calculated by matrix elimination are different from the result obtained by applying lu(D) (Strang pag. 103)

In [41]:
P=pascal(4)

P =

    1    1    1    1
    1    2    3    4
    1    3    6   10
    1    4   10   20



In [42]:
E21 = eye(size(P)); E21(2,1) = -1; P1 = E21*P;  %disp(P1)

In [43]:
E31 = eye(size(P)); E31(3,1) = -1; P2 = E31*P1;  %disp(P2)

In [44]:
E32 = eye(size(P)); E32(3,2) = -2; P3 = E32*P2;  %disp(P3)

In [45]:
E41 = eye(size(P)); E41(4,1) = -1; P4 = E41 * P3; %disp(P4)

In [46]:
E42 = eye(size(P)); E42(4,2) = -3; P5 = E42 * P4; %disp(P5)

In [47]:
E43 = eye(size(P)); E43(4,3) = -3; P6 = E43 * P5; %disp(P6);
U = P6

U =

   1   1   1   1
   0   1   2   3
   0   0   1   3
   0   0   0   1



In [48]:
L = inv(E43*E42*E41*E32*E31*E21)

L =

   1   0   0   0
   1   1   0   0
   1   2   1   0
   1   3   3   1



**Exercise: solve $Px = b, b = [1, 0, 0, 0]$**