# Introduction to linear algebra. Chapter 2

## Matrix multiplication

In [8]:
import numpy as np
np.set_printoptions(precision=3)

In [13]:
np.random.seed(0)
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [14]:
A @ B

array([[0.669, 1.109, 0.843],
       [0.506, 0.837, 0.856],
       [0.758, 1.191, 1.097]])

In [20]:
# 1. The entry in row i and column j of AB is (row i of A) · ( column j of B)
r, c = A.shape
AB = np.empty((r, c))
for i in range(r):
    for j in range(c):
         AB[i,j] = np.dot(A[i,:], B[:,j])
AB

array([[0.669, 1.109, 0.843],
       [0.506, 0.837, 0.856],
       [0.758, 1.191, 1.097]])

In [36]:
# 2. Matrix A times every column of B
AB = np.array([A @ B[:,0], A @ B[:,1], A @ B[:,2]])
AB

array([[0.669, 0.506, 0.758],
       [1.109, 0.837, 1.191],
       [0.843, 0.856, 1.097]])

In [38]:
# 3. Every row of A times matrix B
AB = np.array([B.T@A[0,:], B.T@A[1,:], B.T@A[2,:]])
AB

array([[0.669, 1.109, 0.843],
       [0.506, 0.837, 0.856],
       [0.758, 1.191, 1.097]])

In [46]:
# 4. Multiply columns 1 to n of A times rows 1 to n of B. Add those matrices
AB = np.zeros((r,c))
for i in range(r):
     AB = AB + (A[:,i].T @ B[i,:].T)
AB

array([[2.603, 2.603, 2.603],
       [2.603, 2.603, 2.603],
       [2.603, 2.603, 2.603]])

In [47]:
A[:,0].reshape  @ B[0,:].T

0.873273195292491